function Jb = leg_Jb(th,L4,L5)
%%% [Vleg,r;Vleg,l] = Jb[th1~th8]
%%% th2,th4,th6,th8 --> right 
%%% th1,th3,th5,th7 --> left
th1= th(1);
th2= th(2);
th3= th(3);
th4= th(4);
th5= th(5);
th6= th(6);
th7= th(7);
th8= th(8);
Jb = [                                                                                                         0,          sin(th2)*(L5*sin(th6 + th8) + L4*sin(th6)) - cos(th2)*sin(th4)*(L5*cos(th6 + th8) + L4*cos(th6)),                                                        0,     -cos(th4)*sin(th2)*(L5*cos(th6 + th8) + L4*cos(th6)),                                                                                                         0,          sin(th2)*sin(th4)*(L5*sin(th6 + th8) + L4*sin(th6)) - cos(th2)*(L5*cos(th6 + th8) + L4*cos(th6)),                                                                       0,        L5*sin(th6 + th8)*sin(th2)*sin(th4) - L5*cos(th6 + th8)*cos(th2);
                                                                                                               0,        - cos(th2)*(L5*sin(th6 + th8) + L4*sin(th6)) - sin(th2)*sin(th4)*(L5*cos(th6 + th8) + L4*cos(th6)),                                                        0,      cos(th2)*cos(th4)*(L5*cos(th6 + th8) + L4*cos(th6)),                                                                                                         0,        - sin(th2)*(L5*cos(th6 + th8) + L4*cos(th6)) - cos(th2)*sin(th4)*(L5*sin(th6 + th8) + L4*sin(th6)),                                                                       0,      - L5*cos(th6 + th8)*sin(th2) - L5*sin(th6 + th8)*cos(th2)*sin(th4);
                                                                                                               0,                                                                                                         0,                                                        0,               sin(th4)*(L5*cos(th6 + th8) + L4*cos(th6)),                                                                                                         0,                                                                cos(th4)*(L5*sin(th6 + th8) + L4*sin(th6)),                                                                       0,                                              L5*sin(th6 + th8)*cos(th4);
                                                                                                               0,                                                                                                         1,                                                        0,                                                        0,                                                                                                         0,                                                                                                  sin(th4),                                                                       0,                                                                sin(th4);
                sin(th1)*(L5*sin(th5 + th7) + L4*sin(th5)) - cos(th1)*sin(th3)*(L5*cos(th5 + th7) + L4*cos(th5)),                                                                                                         0,     -cos(th3)*sin(th1)*(L5*cos(th5 + th7) + L4*cos(th5)),                                                        0,          sin(th1)*sin(th3)*(L5*sin(th5 + th7) + L4*sin(th5)) - cos(th1)*(L5*cos(th5 + th7) + L4*cos(th5)),                                                                                                         0,        L5*sin(th5 + th7)*sin(th1)*sin(th3) - L5*cos(th5 + th7)*cos(th1),                                                                       0;
              - cos(th1)*(L5*sin(th5 + th7) + L4*sin(th5)) - sin(th1)*sin(th3)*(L5*cos(th5 + th7) + L4*cos(th5)),                                                                                                         0,      cos(th1)*cos(th3)*(L5*cos(th5 + th7) + L4*cos(th5)),                                                        0,        - sin(th1)*(L5*cos(th5 + th7) + L4*cos(th5)) - cos(th1)*sin(th3)*(L5*sin(th5 + th7) + L4*sin(th5)),                                                                                                         0,      - L5*cos(th5 + th7)*sin(th1) - L5*sin(th5 + th7)*cos(th1)*sin(th3),                                                                       0;
                                                                                                               0,                                                                                                         0,               sin(th3)*(L5*cos(th5 + th7) + L4*cos(th5)),                                                        0,                                                                cos(th3)*(L5*sin(th5 + th7) + L4*sin(th5)),                                                                                                         0,                                              L5*sin(th5 + th7)*cos(th3),                                                                       0;
                                                                                                               1,                                                                                                         0,                                                        0,                                                        0,                                                                                                  sin(th3),                                                                                                         0,                                                                sin(th3),                                                                       0];

end